[workspace]
members = [
    "compiler/qsc",
    "compiler/qsc_ast",
    "compiler/qsc_codegen",
    "compiler/qsc_data_structures",
    "compiler/qsc_eval",
    "compiler/qsc_frontend",
    "compiler/qsc_hir",
    "compiler/qsc_parse",
    "compiler/qsc_passes",
    "fuzz",
    "katas",
    "language_service",
    "library/tests",
    "pip",
    "wasm",
]

[workspace.package]
authors = ["Microsoft"]
homepage = "https://github.com/microsoft/qsharp"
repository = "https://github.com/microsoft/qsharp"
edition = "2021"
license = "MIT"

[workspace.dependencies]
clap = "4.1.8"
criterion = { version = "0.4.0", default-features = false }
enum-iterator = "1.2.0"
env_logger = "0.10.0"
expect-test = "1.4.0"
getrandom = { version = "0.2" }
indoc = "2.0.0"
js-sys = "0.3.61"
libfuzzer-sys = "0.4"
log = "0.4"
miette = "5.6.0"
thiserror = "1.0.39"
num-bigint = "0.4.3"
num-complex = "0.4"
num-traits = "0.2.15"
indenter = "0.2"
regex-lite = "0.1.0"
serde = "1.0"
serde-wasm-bindgen = "0.5"
wasm-bindgen = "0.2.84"
rand = "0.8.5"
serde_json = { version = "1.0.96" }
pyo3 = { version = "0.18", features = ["abi3-py37", "extension-module"] }

[profile.release]
debug = 1
