[package]
name = "qsc_data_structures"
version = "0.0.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
miette = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
