[package]
name = "qsls"
version = "0.0.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dev-dependencies]
expect-test = { workspace = true }
indoc = { workspace = true }

[dependencies]
log = { workspace = true }
miette = { workspace = true }
qsc = { path = "../compiler/qsc" }
enum-iterator = { workspace = true }
regex-lite = { workspace = true }
